function satir_sonu_tusu_turu_belirle () {
	satir_sonu_tusu_turu=3 // eğer ingilizce klavye gibi ince enter ise bayrak =1 eğer turkce q daki gibi ise bayrak=3 tur. 3 parcali vaya tek parcali 		anlaminda. on tanimli olarak 3 parcali turkce q daki gibi buyuk enter tusu secilidir.
}
function sag_el_listesi() {
	var sag_el_karakter= new Array ("1","2","3","4","5","6","Q","W","E","R","T","A","S","D","F","G",">","Z","X","C","V","B","!","'","^","+","%","&");
	return sag_el_karakter; 
}

function sol_el_listesi () {
 	var sol_el_karakter= new Array ("7","8","9","0","Y","U","I","O","P","Ğ","Ü","H","J","K","L","Ş","İ",";","N","M","Ö","Ç",":","/","(",")","=","?","_");
	return sol_el_karakter;
}

function sonraki_tusu_yak(){
    onceki_tusu_sondur();
    if ( (x+1) >= x_uzunluk) return 0;

    if (sifirlandi==true){
        sonrakikarakter=fis[y].charAt(x);
		sifirlandi=false;
    }else {
		sonrakikarakter=fis[y].charAt(x+1);
    }
    sonrakikod= sonrakikarakter.charCodeAt(0);
     switch(sonrakikod) {
        case 32:document.klavye.bosluk.style.background='#c98321';
                document.klavye.bosluk.style.backgroundImage="url('grafikler/standart-bg.png')";
                document["basparmaklar"].src= temel_url + "grafikler/basparmaklar_sari.jpg";
                break;
        case 33:document.klavye.bir.style.background='#c98321';
                document.klavye.bir.style.backgroundImage="url('grafikler/standart-bg.png')";
                document["sol_serce"].src= temel_url + "grafikler/sol_serce_sari.jpg";
                break;
        case 34:document.klavye.ciftirnak.style.background='#c98321';
                document.klavye.ciftirnak.style.backgroundImage="url('grafikler/standart-bg.png')";
                document["sol_serce"].src= temel_url + "grafikler/sol_serce_sari.jpg";
                break;
        case 35:document.klavye.uc.style.background='#c98321';
                document.klavye.uc.style.backgroundImage="url('grafikler/standart-bg.png')";
                document["sol_orta"].src= temel_url + "grafikler/sol_orta_sari.jpg";
                break;
        case 36:document.klavye.dort.style.background='#c98321';
                document.klavye.dort.style.backgroundImage="url('grafikler/standart-bg.png')";
                document["sol_isaret"].src= temel_url + "grafikler/sol_isaret_sari.jpg";
                break;
        case 37:document.klavye.bes.style.background='#c98321';
                document.klavye.bes.style.backgroundImage="url('grafikler/standart-bg.png')";
                document["sol_isaret"].src= temel_url + "grafikler/sol_isaret_sari.jpg";
                break;
        case 38:document.klavye.alti.style.background='#c98321';
                document.klavye.alti.style.backgroundImage="url('grafikler/standart-bg.png')";
                document["sol_isaret"].src= temel_url + "grafikler/sol_isaret_sari.jpg";
                break;
        case 39:document.klavye.iki.style.background='#c98321';
                document.klavye.iki.style.backgroundImage="url('grafikler/standart-bg.png')";
                document["sol_yuzuk"].src= temel_url + "grafikler/sol_yuzuk_sari.jpg";
                break;
        case 40:document.klavye.sekiz.style.background='#c98321';
                document.klavye.sekiz.style.backgroundImage="url('grafikler/standart-bg.png')";
                document["sag_orta"].src= temel_url + "grafikler/sag_orta_sari.jpg";
                break;
        case 41:document.klavye.dokuz.style.background='#c98321';
                document.klavye.dokuz.style.backgroundImage="url('grafikler/standart-bg.png')";
                document["sag_yuzuk"].src= temel_url + "grafikler/sag_yuzuk_sari.jpg";
                break;
        case 42:document.klavye.yildiz.style.background='#c98321';
                document.klavye.yildiz.style.backgroundImage="url('grafikler/standart-bg.png')";
                document["sag_serce"].src= temel_url + "grafikler/sag_serce_sari.jpg";
                break;
        case 43:document.klavye.dort.style.background='#c98321';
                document.klavye.dort.style.backgroundImage="url('grafikler/standart-bg.png')";
                document["sol_isaret"].src="./sol_isaret_sari.jpg";
                break;
        case 44:document.klavye.virgul.style.background='#c98321';
                document.klavye.virgul.style.backgroundImage="url('grafikler/standart-bg.png')";
                document["sag_serce"].src= temel_url + "grafikler/sag_serce_sari.jpg";
                break;
        case 45:document.klavye.eksi.style.background='#c98321';
                document.klavye.eksi.style.backgroundImage="url('grafikler/standart-bg.png')";
                document["sag_serce"].src= temel_url + "grafikler/sag_serce_sari.jpg";
                break;
        case 46:document.klavye.nokta.style.background='#c98321';
                document.klavye.nokta.style.backgroundImage="url('grafikler/standart-bg.png')";
                document["sag_serce"].src= temel_url + "grafikler/sag_serce_sari.jpg";
                break;
        case 47:document.klavye.yedi.style.background='#c98321';
                document.klavye.yedi.style.backgroundImage="url('grafikler/standart-bg.png')";
                document["sag_isaret"].src= temel_url + "grafikler/sag_isaret_sari.jpg";
                break;
        case 48:document.klavye.sifir.style.background='#c98321';
                document.klavye.sifir.style.backgroundImage="url('grafikler/standart-bg.png')";
                document["sag_serce"].src= temel_url + "grafikler/sag_serce_sari.jpg";
                break;
        case 49:document.klavye.bir.style.background='#c98321';
                document.klavye.bir.style.backgroundImage="url('grafikler/standart-bg.png')";
                document["sol_serce"].src= temel_url + "grafikler/sol_serce_sari.jpg";
                break;
        case 50:document.klavye.iki.style.background='#c98321';
                document.klavye.iki.style.backgroundImage="url('grafikler/standart-bg.png')";
                document["sol_yuzuk"].src= temel_url + "grafikler/sol_yuzuk_sari.jpg";
                break;
        case 51:document.klavye.uc.style.background='#c98321';
                document.klavye.uc.style.backgroundImage="url('grafikler/standart-bg.png')";
                document["sol_orta"].src= temel_url + "grafikler/sol_orta_sari.jpg";
                break;
        case 52:document.klavye.dort.style.background='#c98321';
                document.klavye.dort.style.backgroundImage="url('grafikler/standart-bg.png')";
                document["sol_isaret"].src= temel_url + "grafikler/sol_isaret_sari.jpg";
                break;
        case 53:document.klavye.bes.style.background='#c98321';
                document.klavye.bes.style.backgroundImage="url('grafikler/standart-bg.png')";
                document["sol_isaret"].src= temel_url + "grafikler/sol_isaret_sari.jpg";
                break;
        case 54:document.klavye.alti.style.background='#c98321';
                document.klavye.alti.style.backgroundImage="url('grafikler/standart-bg.png')";
                document["sol_isaret"].src= temel_url + "grafikler/sol_isaret_sari.jpg";
                break;
        case 55:document.klavye.yedi.style.background='#c98321';
                document.klavye.yedi.style.backgroundImage="url('grafikler/standart-bg.png')";
                document["sag_isaret"].src= temel_url + "grafikler/sag_isaret_sari.jpg";
                break;
        case 56:document.klavye.sekiz.style.background='#c98321';
                document.klavye.sekiz.style.backgroundImage="url('grafikler/standart-bg.png')";
                document["sag_orta"].src= temel_url + "grafikler/sag_orta_yeni.jpg";
                break;
        case 57:document.klavye.dokuz.style.background='#c98321';
                document.klavye.dokuz.style.backgroundImage="url('grafikler/standart-bg.png')";
                document["sag_yuzuk"].src= temel_url + "grafikler/sag_yuzuk_sari.jpg";
                break;
        case 58:document.klavye.nokta.style.background='#c98321';
                document.klavye.nokta.style.backgroundImage="url('grafikler/standart-bg.png')";
                document["sag_serce"].src= temel_url + "grafikler/sag_serce_sari.jpg";
                break;
        case 59:document.klavye.virgul.style.background='#c98321';
                document.klavye.virgul.style.backgroundImage="url('grafikler/standart-bg.png')";
                document["sag_serce"].src= temel_url + "grafikler/sag_serce_sari.jpg";
                break;
        case 60:document.klavye.kucuktur.style.background='#c98321';
                document.klavye.kucuktur.style.backgroundImage="url('grafikler/standart-bg.png')";
                document["sol_serce"].src= temel_url + "grafikler/sol_serce_sari.jpg";
                break;
        case 61:document.klavye.sifir.style.background='#c98321';
                document.klavye.sifir.style.backgroundImage="url('grafikler/standart-bg.png')";
                document["sag_serce"].src= temel_url + "grafikler/sag_serce_sari.jpg";
                break;
        case 62:document.klavye.kucuktur.style.background='#c98321';
                document.klavye.kucuktur.style.backgroundImage="url('grafikler/standart-bg.png')";
                document["sol_serce"].src= temel_url + "grafikler/sol_serce_sari.jpg";
                break;
        case 63:document.klavye.yildiz.style.background='#c98321';
                document.klavye.yildiz.style.backgroundImage="url('grafikler/standart-bg.png')";
                document["sag_serce"].src= temel_url + "grafikler/sag_serce_sari.jpg";
                break;
        case 64:document.klavye.Q.style.background='#c98321';
                document.klavye.Q.style.backgroundImage="url('grafikler/standart-bg.png')";
                document["sol_serce"].src= temel_url + "grafikler/sol_serce_sari.jpg";
                break;
        case 65:document.klavye.A.style.background='#c98321';
                document.klavye.A.style.backgroundImage="url('grafikler/standart-bg.png')";
                document["sol_serce"].src= temel_url + "grafikler/sol_serce_sari.jpg";
                break;
        case 66:document.klavye.B.style.background='#c98321';
                document.klavye.B.style.backgroundImage="url('grafikler/standart-bg.png')";
                document["sol_isaret"].src= temel_url + "grafikler/sol_isaret_sari.jpg";
                break;
        case 67:document.klavye.C.style.background='#c98321';
                document.klavye.C.style.backgroundImage="url('grafikler/standart-bg.png')";
                document["sol_orta"].src= temel_url + "grafikler/sol_orta_sari.jpg";
                break;
        case 68:document.klavye.D.style.background='#c98321';
                document.klavye.D.style.backgroundImage="url('grafikler/standart-bg.png')";
                document["sol_orta"].src= temel_url + "grafikler/sol_orta_sari.jpg";
                break;
        case 69:document.klavye.E.style.background='#c98321';
                document.klavye.E.style.backgroundImage="url('grafikler/standart-bg.png')";
                document["sol_orta"].src= temel_url + "grafikler/sol_orta_sari.jpg";
                break;
        case 70:document.klavye.F.style.background='#c98321';
                document.klavye.F.style.backgroundImage="url('grafikler/standart-bg.png')";
                document["sol_isaret"].src= temel_url + "grafikler/sol_isaret_sari.jpg";
                break;
        case 71:document.klavye.G.style.background='#c98321';
                document.klavye.G.style.backgroundImage="url('grafikler/standart-bg.png')";
                document["sol_isaret"].src= temel_url + "grafikler/sol_isaret_sari.jpg";
                break;
        case 72:document.klavye.H.style.background='#c98321';
                document.klavye.H.style.backgroundImage="url('grafikler/standart-bg.png')";
                document["sag_isaret"].src= temel_url + "grafikler/sag_isaret_sari.jpg";
                break;
        case 73:document.klavye.I.style.background='#c98321';
                document.klavye.I.style.backgroundImage="url('grafikler/standart-bg.png')";
                document["sag_orta"].src= temel_url + "grafikler/sag_orta_sari.jpg";
                break;
        case 74:document.klavye.J.style.background='#c98321';
                document.klavye.J.style.backgroundImage="url('grafikler/standart-bg.png')";
                document["sag_isaret"].src= temel_url + "grafikler/sag_isaret_sari.jpg";
                break;
        case 75:document.klavye.K.style.background='#c98321';
                document.klavye.K.style.backgroundImage="url('grafikler/standart-bg.png')";
                document["sag_orta"].src= temel_url + "grafikler/sag_orta_sari.jpg";
                break;
        case 76:document.klavye.L.style.background='#c98321';
                document.klavye.L.style.backgroundImage="url('grafikler/standart-bg.png')";
                document["sag_yuzuk"].src= temel_url + "grafikler/sag_yuzuk_sari.jpg";
                break;
        case 77:document.klavye.M.style.background='#c98321';
                document.klavye.M.style.backgroundImage="url('grafikler/standart-bg.png')";
                document["sag_isaret"].src= temel_url + "grafikler/sag_isaret_sari.jpg";
                break;
        case 78:document.klavye.N.style.background='#c98321';
                document.klavye.N.style.backgroundImage="url('grafikler/standart-bg.png')";
                document["sag_isaret"].src= temel_url + "grafikler/sag_isaret_sari.jpg";
                break;
        case 79:document.klavye.O.style.background='#c98321';
                document.klavye.O.style.backgroundImage="url('grafikler/standart-bg.png')";
                document["sag_yuzuk"].src= temel_url + "grafikler/sag_yuzuk_sari.jpg";
                break;
        case 80:document.klavye.P.style.background='#c98321';
                document.klavye.P.style.backgroundImage="url('grafikler/standart-bg.png')";
                document["sag_isaret"].src= temel_url + "grafikler/sag_isaret_sari.jpg";
                break;
        case 81:document.klavye.Q.style.background='#c98321';
                document.klavye.Q.style.backgroundImage="url('grafikler/standart-bg.png')";
                document["sol_serce"].src= temel_url + "grafikler/sol_serce_sari.jpg";
                break;
        case 82:document.klavye.R.style.background='#c98321';
                document.klavye.R.style.backgroundImage="url('grafikler/standart-bg.png')";
                document["sol_isaret"].src= temel_url + "grafikler/sol_isaret_sari.jpg";
                break;
        case 83:document.klavye.S.style.background='#c98321';
                document.klavye.S.style.backgroundImage="url('grafikler/standart-bg.png')";
                document["sol_yuzuk"].src= temel_url + "grafikler/sol_yuzuk_sari.jpg";
                break;
        case 84:document.klavye.T.style.background='#c98321';
                document.klavye.T.style.backgroundImage="url('grafikler/standart-bg.png')";
                document["sol_isaret"].src= temel_url + "grafikler/sol_isaret_sari.jpg";
                break;
        case 85:document.klavye.U.style.background='#c98321';
                document.klavye.U.style.backgroundImage="url('grafikler/standart-bg.png')";
                document["sag_isaret"].src= temel_url + "grafikler/sag_isaret_sari.jpg";
                break;
        case 86:document.klavye.V.style.background='#c98321';
                document.klavye.V.style.backgroundImage="url('grafikler/standart-bg.png')";
                document["sol_isaret"].src= temel_url + "grafikler/sol_isaret_sari.jpg";
                break;
        case 87:document.klavye.W.style.background='#c98321';
                document.klavye.W.style.backgroundImage="url('grafikler/standart-bg.png')";
                document["sol_yuzuk"].src= temel_url + "grafikler/sol_yuzuk_sari.jpg";
                break;
        case 88:document.klavye.X.style.background='#c98321';
                document.klavye.X.style.backgroundImage="url('grafikler/standart-bg.png')";
                document["sol_yuzuk"].src= temel_url + "grafikler/sol_yuzuk_sari.jpg";
                break;
        case 89:document.klavye.Y.style.background='#c98321';
                document.klavye.Y.style.backgroundImage="url('grafikler/standart-bg.png')";
                document["sag_isaret"].src= temel_url + "grafikler/sag_isaret_sari.jpg";
                break;
        case 90:document.klavye.Z.style.background='#c98321';
                document.klavye.Z.style.backgroundImage="url('grafikler/standart-bg.png')";
                document["sol_serce"].src= temel_url + "grafikler/sol_serce_sari.jpg";
                break;
        case 91:document.klavye.sekiz.style.background='#c98321';
                document.klavye.sekiz.style.backgroundImage="url('grafikler/standart-bg.png')";
                document["sag_orta"].src= temel_url + "grafikler/sag_orta_sari.jpg";
                break;
        case 92:document.klavye.yildiz.style.background='#c98321';
                document.klavye.yildiz.style.backgroundImage="url('grafikler/standart-bg.png')";
                document["sag_serce"].src= temel_url + "grafikler/sag_serce_sari.jpg";
                break;
        case 93:document.klavye.dokuz.style.background='#c98321';
                document.klavye.dokuz.style.backgroundImage="url('grafikler/standart-bg.png')";
                document["sag_yuzuk"].src= temel_url + "grafikler/sag_yuzuk_sari.jpg";
                break;
        case 94:document.klavye.uc.style.background='#c98321';
                document.klavye.uc.style.backgroundImage="url('grafikler/standart-bg.png')";
                document["sol_orta"].src= temel_url + "grafikler/sol_orta_sari.jpg";
                break;
        case 95:document.klavye.eksi.style.background='#c98321';
                document.klavye.eksi.style.backgroundImage="url('grafikler/standart-bg.png')";
                document["sag_serce"].src= temel_url + "grafikler/sag_serce_sari.jpg";
                break;
        case 96:document.klavye.iki.style.background='#c98321';
                document.klavye.iki.style.backgroundImage="url('grafikler/standart-bg.png')";
                document["sol_yuzuk"].src= temel_url + "grafikler/sol_yuzuk_sari.jpg";
                break;
        case 97:document.klavye.A.style.background='#c98321';
                document.klavye.A.style.backgroundImage="url('grafikler/standart-bg.png')";
                document["sol_serce"].src= temel_url + "grafikler/sol_serce_sari.jpg";
                break;
        case 98:document.klavye.B.style.background='#c98321';
                document.klavye.B.style.backgroundImage="url('grafikler/standart-bg.png')";
                document["sol_isaret"].src= temel_url + "grafikler/sol_isaret_sari.jpg";
                break;
        case 99:document.klavye.C.style.background='#c98321';
                document.klavye.C.style.backgroundImage="url('grafikler/standart-bg.png')";
                document.klavye.C.style.backgroundImage="url('grafikler/standart-bg.png')";
                document["sol_orta"].src= temel_url + "grafikler/sol_orta_sari.jpg";
                break;
        case 100:document.klavye.D.style.background='#c98321';
                document.klavye.D.style.backgroundImage="url('grafikler/standart-bg.png')";
                 document["sol_orta"].src= temel_url + "grafikler/sol_orta_sari.jpg";
                 break;
        case 101:document.klavye.E.style.background='#c98321';
                document.klavye.E.style.backgroundImage="url('grafikler/standart-bg.png')";
                 document["sol_orta"].src= temel_url + "grafikler/sol_orta_sari.jpg";
                 break;
        case 102:document.klavye.F.style.background='#c98321';
                document.klavye.F.style.backgroundImage="url('grafikler/standart-bg.png')";
                 document["sol_isaret"].src= temel_url + "grafikler/sol_isaret_sari.jpg";
                 break;
        case 103:document.klavye.G.style.background='#c98321';
                document.klavye.G.style.backgroundImage="url('grafikler/standart-bg.png')";
                 document["sol_isaret"].src= temel_url + "grafikler/sol_isaret_sari.jpg";
                 break;
        case 104:document.klavye.H.style.background='#c98321';
                document.klavye.H.style.backgroundImage="url('grafikler/standart-bg.png')";
                 document["sag_isaret"].src= temel_url + "grafikler/sag_isaret_sari.jpg";
                 break;
        case 105:document.klavye.ii.style.background='#c98321';
                document.klavye.ii.style.backgroundImage="url('grafikler/standart-bg.png')";
                 document["sag_serce"].src= temel_url + "grafikler/sag_serce_sari.jpg";
                 break;
        case 106:document.klavye.J.style.background='#c98321';
                document.klavye.J.style.backgroundImage="url('grafikler/standart-bg.png')";
                 document["sag_isaret"].src= temel_url + "grafikler/sag_isaret_sari.jpg";
                 break;
        case 107:document.klavye.K.style.background='#c98321';
                 document.klavye.K.style.backgroundImage="url('grafikler/standart-bg.png')";
                 document["sag_orta"].src= temel_url + "grafikler/sag_orta_sari.jpg";
                 break;
        case 108:document.klavye.L.style.background='#c98321';
                 document.klavye.L.style.backgroundImage="url('grafikler/standart-bg.png')";
                 document["sag_yuzuk"].src= temel_url + "grafikler/sag_yuzuk_sari.jpg";
                 break;
        case 109:document.klavye.M.style.background='#c98321';
                 document.klavye.M.style.backgroundImage="url('grafikler/standart-bg.png')";
                 document["sag_isaret"].src= temel_url + "grafikler/sag_isaret_sari.jpg";
                 break;
        case 110:document.klavye.N.style.background='#c98321';
                 document.klavye.N.style.backgroundImage="url('grafikler/standart-bg.png')";
                 document["sag_isaret"].src= temel_url + "grafikler/sag_isaret_sari.jpg";
                 break;
        case 111:document.klavye.O.style.background='#c98321';
                 document.klavye.O.style.backgroundImage="url('grafikler/standart-bg.png')";
                 document.klavye.A.style.backgroundImage="url('grafikler/standart-bg.png')";
                 document["sag_yuzuk"].src= temel_url + "grafikler/sag_yuzuk_sari.jpg";
                 break;
        case 112:document.klavye.P.style.background='#c98321';
                 document.klavye.P.style.backgroundImage="url('grafikler/standart-bg.png')";
                 document["sag_serce"].src= temel_url + "grafikler/sag_serce_sari.jpg";
                 break;
        case 113:document.klavye.Q.style.background='#c98321';
                 document.klavye.Q.style.backgroundImage="url('grafikler/standart-bg.png')";
                 document["sol_serce"].src= temel_url + "grafikler/sol_serce_sari.jpg";
                 break;
        case 114:document.klavye.R.style.background='#c98321';
                 document.klavye.R.style.backgroundImage="url('grafikler/standart-bg.png')";
                 document["sol_isaret"].src= temel_url + "grafikler/sol_isaret_sari.jpg";
                 break;
        case 115:document.klavye.S.style.background='#c98321';
                 document.klavye.S.style.backgroundImage="url('grafikler/standart-bg.png')";
                 document["sol_yuzuk"].src= temel_url + "grafikler/sol_yuzuk_sari.jpg";
                 break;
        case 116:document.klavye.T.style.background='#c98321';
                 document.klavye.T.style.backgroundImage="url('grafikler/standart-bg.png')";
                 document["sol_isaret"].src= temel_url + "grafikler/sol_isaret_sari.jpg";
                 break;
        case 117:document.klavye.U.style.background='#c98321';
                 document.klavye.U.style.backgroundImage="url('grafikler/standart-bg.png')";
                 document["sag_isaret"].src= temel_url + "grafikler/sag_isaret_sari.jpg";
                 break;
        case 118:document.klavye.V.style.background='#c98321';
                 document.klavye.V.style.backgroundImage="url('grafikler/standart-bg.png')";
                 document["sol_isaret"].src= temel_url + "grafikler/sol_isaret_sari.jpg";
                 break;
        case 119:document.klavye.W.style.background='#c98321';
                 document.klavye.W.style.backgroundImage="url('grafikler/standart-bg.png')";
                 document["sol_yuzuk"].src= temel_url + "grafikler/sol_yuzuk_sari.jpg";
                 break;
        case 120:document.klavye.X.style.background='#c98321';
                 document.klavye.X.style.backgroundImage="url('grafikler/standart-bg.png')";
                 document["sol_yuzuk"].src= temel_url + "grafikler/sol_yuzuk_sari.jpg";
                 break;
        case 121:document.klavye.Y.style.background='#c98321';
                 document.klavye.Y.style.backgroundImage="url('grafikler/standart-bg.png')";
                 document["sag_isaret"].src= temel_url + "grafikler/sag_isaret_sari.jpg";
                 break;
        case 122:document.klavye.Z.style.background='#c98321';
                 document.klavye.Z.style.backgroundImage="url('grafikler/standart-bg.png')";
                 document["sol_serce"].src= temel_url + "grafikler/sol_serce_sari.jpg";
                 break;
        case 123:document.klavye.yedi.style.background='#c98321';
                 document.klavye.yedi.style.backgroundImage="url('grafikler/standart-bg.png')";
                 document["sag_isaret"].src= temel_url + "grafikler/sag_isaret_sari.jpg";
                 break;
        case 124:document.klavye.kucuktur.style.background='#c98321';
                 document.klavye.kucuktur.style.backgroundImage="url('grafikler/standart-bg.png')";
                 document["sol_serce"].src= temel_url + "grafikler/sol_serce_sari.jpg";
                 break;
        case 125:document.klavye.sifir.style.background='#c98321';
                 document.klavye.sifir.style.backgroundImage="url('grafikler/standart-bg.png')";
                 document["sag_serce"].src= temel_url + "grafikler/sag_serce_sari.jpg";
                 break;
        case 126:document.klavye.uu.style.background='#c98321';
                 document.klavye.uu.style.backgroundImage="url('grafikler/standart-bg.png')";
                 document["sag_serce"].src= temel_url + "grafikler/sag_serce_sari.jpg";
                 break;
        case 127:document.klavye.del.style.background='#c98321';
                 document.klavye.del.style.backgroundImage="url('grafikler/standart-bg.png')";
                 document["sag_serce"].src= temel_url + "grafikler/sag_serce_sari.jpg";
                 break;
        case 287:document.klavye.gg.style.background='#c98321';
                 document.klavye.gg.style.backgroundImage="url('grafikler/standart-bg.png')";
                 document["sag_serce"].src= temel_url + "grafikler/sag_serce_sari.jpg";
                 break;
        case 286:document.klavye.gg.style.background='#c98321';
                 document.klavye.gg.style.backgroundImage="url('grafikler/standart-bg.png')";
                 document["sag_serce"].src= temel_url + "grafikler/sag_serce_sari.jpg";
                 break;
        case 252:document.klavye.uu.style.background='#c98321';
                 document.klavye.uu.style.backgroundImage="url('grafikler/standart-bg.png')";
                 document["sag_serce"].src= temel_url + "grafikler/sag_serce_sari.jpg";
                 break;
        case 220:document.klavye.uu.style.background='#c98321';
                 document.klavye.uu.style.backgroundImage="url('grafikler/standart-bg.png')";
                 document["sag_serce"].src= temel_url + "grafikler/sag_serce_sari.jpg";
                 break;
        case 351:document.klavye.ss.style.background='#c98321';
                 document.klavye.ss.style.backgroundImage="url('grafikler/standart-bg.png')";
                 document["sag_serce"].src= temel_url + "grafikler/sag_serce_sari.jpg";
                 break;
        case 350:document.klavye.ss.style.background='#c98321';
                 document.klavye.ss.style.backgroundImage="url('grafikler/standart-bg.png')";
                 document["sag_serce"].src= temel_url + "grafikler/sag_serce_sari.jpg";
                 break;
        case 305:document.klavye.I.style.background='#c98321';
                 document.klavye.I.style.backgroundImage="url('grafikler/standart-bg.png')";
                 document["sag_orta"].src= temel_url + "grafikler/sag_orta_sari.jpg";
                 break;
        case 304:document.klavye.ii.style.background='#c98321';
                 document.klavye.ii.style.backgroundImage="url('grafikler/standart-bg.png')";
                 document["sag_serce"].src= temel_url + "grafikler/sag_serce_sari.jpg";
                 break;
        case 246:document.klavye.oo.style.background='#c98321';
                 document.klavye.oo.style.backgroundImage="url('grafikler/standart-bg.png')";
                 document["sag_orta"].src= temel_url + "grafikler/sag_orta_sari.jpg";
                 break;
        case 214:document.klavye.oo.style.background='#c98321';
                 document.klavye.oo.style.backgroundImage="url('grafikler/standart-bg.png')";
                 document["sag_orta"].src= temel_url + "grafikler/sag_orta_sari.jpg";
                 break;
        case 231:document.klavye.cc.style.background='#c98321';
                 document.klavye.cc.style.backgroundImage="url('grafikler/standart-bg.png')";
                 document["sag_yuzuk"].src= temel_url + "grafikler/sag_yuzuk_sari.jpg";
                 break;
        case 199:document.klavye.cc.style.background='#c98321';
                 document.klavye.cc.style.backgroundImage="url('grafikler/standart-bg.png')";
                 document["sag_yuzuk"].src= temel_url + "grafikler/sag_yuzuk_sari.jpg";
                 break;
       }
       oncekikod=sonrakikod;
}

function onceki_tusu_sondur(){
     if (oncekikod==null)return 0;
     switch(oncekikod) {
        case 32:document.klavye.bosluk.style.background='black';
                document.klavye.bosluk.style.backgroundImage="url('grafikler/standart-bg.png')";
                document["basparmaklar"].src= temel_url + "grafikler/basparmaklar.jpg";
                break;
        case 33:document.klavye.bir.style.background='black';
                document.klavye.bir.style.backgroundImage="url('grafikler/standart-bg.png')";
                document["sol_serce"].src= temel_url + "grafikler/sol_serce.jpg";
                break;
        case 34:document.klavye.ciftirnak.style.background='black';
                document.klavye.ciftirnak.style.backgroundImage="url('grafikler/standart-bg.png')";
                document["sol_serce"].src= temel_url + "grafikler/sol_serce.jpg";
                break;
        case 35:document.klavye.uc.style.background='black';
                document.klavye.uc.style.backgroundImage="url('grafikler/standart-bg.png')";
                document["sol_orta"].src= temel_url + "grafikler/sol_orta.jpg";
                break;
        case 36:document.klavye.dort.style.background='black';
                document.klavye.dort.style.backgroundImage="url('grafikler/standart-bg.png')";
                document["sol_isaret"].src= temel_url + "grafikler/sol_isaret.jpg";
                break;
        case 37:document.klavye.bes.style.background='black';
                document.klavye.bes.style.backgroundImage="url('grafikler/standart-bg.png')";
                document["sol_isaret"].src= temel_url + "grafikler/sol_isaret.jpg";
                break;
        case 38:document.klavye.alti.style.background='black';
                document.klavye.alti.style.backgroundImage="url('grafikler/standart-bg.png')";
                document["sol_isaret"].src= temel_url + "grafikler/sol_isaret.jpg";
                break;
        case 39:document.klavye.iki.style.background='black';
                document.klavye.iki.style.backgroundImage="url('grafikler/standart-bg.png')";
                document["sol_yuzuk"].src= temel_url + "grafikler/sol_yuzuk.jpg";
                break;
        case 40:document.klavye.sekiz.style.background='black';
                document.klavye.sekiz.style.backgroundImage="url('grafikler/standart-bg.png')";
                document["sag_orta"].src= temel_url + "grafikler/sag_orta.jpg";
                break;
        case 41:document.klavye.dokuz.style.background='black';
                document.klavye.dokuz.style.backgroundImage="url('grafikler/standart-bg.png')";
                document["sag_yuzuk"].src= temel_url + "grafikler/sag_yuzuk.jpg";
                break;
        case 42:document.klavye.yildiz.style.background='black';
                document.klavye.yildiz.style.backgroundImage="url('grafikler/standart-bg.png')";
                document["sag_serce"].src= temel_url + "grafikler/sag_serce.jpg";
                break;
        case 43:document.klavye.dort.style.background='black';
                document.klavye.dort.style.backgroundImage="url('grafikler/standart-bg.png')";
                document["sol_isaret"].src="./sol_isaret.jpg";
                break;
        case 44:document.klavye.virgul.style.background='black';
                document.klavye.virgul.style.backgroundImage="url('grafikler/standart-bg.png')";
                document["sag_serce"].src= temel_url + "grafikler/sag_serce.jpg";
                break;
        case 45:document.klavye.eksi.style.background='black';
                document.klavye.eksi.style.backgroundImage="url('grafikler/standart-bg.png')";
                document["sag_serce"].src= temel_url + "grafikler/sag_serce.jpg";
                break;
        case 46:document.klavye.nokta.style.background='black';
                document.klavye.nokta.style.backgroundImage="url('grafikler/standart-bg.png')";
                document["sag_serce"].src= temel_url + "grafikler/sag_serce.jpg";
                break;
        case 47:document.klavye.yedi.style.background='black';
                document.klavye.yedi.style.backgroundImage="url('grafikler/standart-bg.png')";
                document["sag_isaret"].src= temel_url + "grafikler/sag_isaret.jpg";
                break;
        case 48:document.klavye.sifir.style.background='black';
                document.klavye.sifir.style.backgroundImage="url('grafikler/standart-bg.png')";
                document["sag_serce"].src= temel_url + "grafikler/sag_serce.jpg";
                break;
        case 49:document.klavye.bir.style.background='black';
                document.klavye.bir.style.backgroundImage="url('grafikler/standart-bg.png')";
                document["sol_serce"].src= temel_url + "grafikler/sol_serce.jpg";
                break;
        case 50:document.klavye.iki.style.background='black';
                document.klavye.iki.style.backgroundImage="url('grafikler/standart-bg.png')";
                document["sol_yuzuk"].src= temel_url + "grafikler/sol_yuzuk.jpg";
                break;
        case 51:document.klavye.uc.style.background='black';
                document.klavye.uc.style.backgroundImage="url('grafikler/standart-bg.png')";
                document["sol_orta"].src= temel_url + "grafikler/sol_orta.jpg";
                break;
        case 52:document.klavye.dort.style.background='black';
                document.klavye.dort.style.backgroundImage="url('grafikler/standart-bg.png')";
                document["sol_isaret"].src= temel_url + "grafikler/sol_isaret.jpg";
                break;
        case 53:document.klavye.bes.style.background='black';
                document.klavye.bes.style.backgroundImage="url('grafikler/standart-bg.png')";
                document["sol_isaret"].src= temel_url + "grafikler/sol_isaret.jpg";
                break;
        case 54:document.klavye.alti.style.background='black';
                document.klavye.alti.style.backgroundImage="url('grafikler/standart-bg.png')";
                document["sol_isaret"].src= temel_url + "grafikler/sol_isaret.jpg";
                break;
        case 55:document.klavye.yedi.style.background='black';
                document.klavye.yedi.style.backgroundImage="url('grafikler/standart-bg.png')";
                document["sag_isaret"].src= temel_url + "grafikler/sag_isaret.jpg";
                break;
        case 56:document.klavye.sekiz.style.background='black';
                document.klavye.sekiz.style.backgroundImage="url('grafikler/standart-bg.png')";
                document["sag_orta"].src= temel_url + "grafikler/sag_orta_yeni.jpg";
                break;
        case 57:document.klavye.dokuz.style.background='black';
                document.klavye.dokuz.style.backgroundImage="url('grafikler/standart-bg.png')";
                document["sag_yuzuk"].src= temel_url + "grafikler/sag_yuzuk.jpg";
                break;
        case 58:document.klavye.nokta.style.background='black';
                document.klavye.nokta.style.backgroundImage="url('grafikler/standart-bg.png')";
                document["sag_serce"].src= temel_url + "grafikler/sag_serce.jpg";
                break;
        case 59:document.klavye.virgul.style.background='black';
                document.klavye.virgul.style.backgroundImage="url('grafikler/standart-bg.png')";
                document["sag_serce"].src= temel_url + "grafikler/sag_serce.jpg";
                break;
        case 60:document.klavye.kucuktur.style.background='black';
                document.klavye.kucuktur.style.backgroundImage="url('grafikler/standart-bg.png')";
                document["sol_serce"].src= temel_url + "grafikler/sol_serce.jpg";
                break;
        case 61:document.klavye.sifir.style.background='black';
                document.klavye.sifir.style.backgroundImage="url('grafikler/standart-bg.png')";
                document["sag_serce"].src= temel_url + "grafikler/sag_serce.jpg";
                break;
        case 62:document.klavye.kucuktur.style.background='black';
                document.klavye.kucuktur.style.backgroundImage="url('grafikler/standart-bg.png')";
                document["sol_serce"].src= temel_url + "grafikler/sol_serce.jpg";
                break;
        case 63:document.klavye.yildiz.style.background='black';
                document.klavye.yildiz.style.backgroundImage="url('grafikler/standart-bg.png')";
                document["sag_serce"].src= temel_url + "grafikler/sag_serce.jpg";
                break;
        case 64:document.klavye.Q.style.background='black';
                document.klavye.Q.style.backgroundImage="url('grafikler/standart-bg.png')";
                document["sol_serce"].src= temel_url + "grafikler/sol_serce.jpg";
                break;
        case 65:document.klavye.A.style.background='black';
                document.klavye.A.style.backgroundImage="url('grafikler/standart-bg.png')";
                document["sol_serce"].src= temel_url + "grafikler/sol_serce.jpg";
                break;
        case 66:document.klavye.B.style.background='black';
                document.klavye.B.style.backgroundImage="url('grafikler/standart-bg.png')";
                document["sol_isaret"].src= temel_url + "grafikler/sol_isaret.jpg";
                break;
        case 67:document.klavye.C.style.background='black';
                document.klavye.C.style.backgroundImage="url('grafikler/standart-bg.png')";
                document["sol_orta"].src= temel_url + "grafikler/sol_orta.jpg";
                break;
        case 68:document.klavye.D.style.background='black';
                document.klavye.D.style.backgroundImage="url('grafikler/standart-bg.png')";
                document["sol_orta"].src= temel_url + "grafikler/sol_orta.jpg";
                break;
        case 69:document.klavye.E.style.background='black';
                document.klavye.E.style.backgroundImage="url('grafikler/standart-bg.png')";
                document["sol_orta"].src= temel_url + "grafikler/sol_orta.jpg";
                break;
        case 70:document.klavye.F.style.background='black';
                document.klavye.F.style.backgroundImage="url('grafikler/standart-bg.png')";
                document["sol_isaret"].src= temel_url + "grafikler/sol_isaret.jpg";
                break;
        case 71:document.klavye.G.style.background='black';
                document.klavye.G.style.backgroundImage="url('grafikler/standart-bg.png')";
                document["sol_isaret"].src= temel_url + "grafikler/sol_isaret.jpg";
                break;
        case 72:document.klavye.H.style.background='black';
                document.klavye.H.style.backgroundImage="url('grafikler/standart-bg.png')";
                document["sag_isaret"].src= temel_url + "grafikler/sag_isaret.jpg";
                break;
        case 73:document.klavye.I.style.background='black';
                document.klavye.I.style.backgroundImage="url('grafikler/standart-bg.png')";
                document["sag_orta"].src= temel_url + "grafikler/sag_orta.jpg";
                break;
        case 74:document.klavye.J.style.background='black';
                document.klavye.J.style.backgroundImage="url('grafikler/standart-bg.png')";
                document["sag_isaret"].src= temel_url + "grafikler/sag_isaret.jpg";
                break;
        case 75:document.klavye.K.style.background='black';
                document.klavye.K.style.backgroundImage="url('grafikler/standart-bg.png')";
                document["sag_orta"].src= temel_url + "grafikler/sag_orta.jpg";
                break;
        case 76:document.klavye.L.style.background='black';
                document.klavye.L.style.backgroundImage="url('grafikler/standart-bg.png')";
                document["sag_yuzuk"].src= temel_url + "grafikler/sag_yuzuk.jpg";
                break;
        case 77:document.klavye.M.style.background='black';
                document.klavye.M.style.backgroundImage="url('grafikler/standart-bg.png')";
                document["sag_isaret"].src= temel_url + "grafikler/sag_isaret.jpg";
                break;
        case 78:document.klavye.N.style.background='black';
                document.klavye.N.style.backgroundImage="url('grafikler/standart-bg.png')";
                document["sag_isaret"].src= temel_url + "grafikler/sag_isaret.jpg";
                break;
        case 79:document.klavye.O.style.background='black';
                document.klavye.O.style.backgroundImage="url('grafikler/standart-bg.png')";
                document["sag_yuzuk"].src= temel_url + "grafikler/sag_yuzuk.jpg";
                break;
        case 80:document.klavye.P.style.background='black';
                document.klavye.P.style.backgroundImage="url('grafikler/standart-bg.png')";
                document["sag_isaret"].src= temel_url + "grafikler/sag_isaret.jpg";
                break;
        case 81:document.klavye.Q.style.background='black';
                document.klavye.Q.style.backgroundImage="url('grafikler/standart-bg.png')";
                document["sol_serce"].src= temel_url + "grafikler/sol_serce.jpg";
                break;
        case 82:document.klavye.R.style.background='black';
                document.klavye.R.style.backgroundImage="url('grafikler/standart-bg.png')";
                document["sol_isaret"].src= temel_url + "grafikler/sol_isaret.jpg";
                break;
        case 83:document.klavye.S.style.background='black';
                document.klavye.S.style.backgroundImage="url('grafikler/standart-bg.png')";
                document["sol_yuzuk"].src= temel_url + "grafikler/sol_yuzuk.jpg";
                break;
        case 84:document.klavye.T.style.background='black';
                document.klavye.T.style.backgroundImage="url('grafikler/standart-bg.png')";
                document["sol_isaret"].src= temel_url + "grafikler/sol_isaret.jpg";
                break;
        case 85:document.klavye.U.style.background='black';
                document.klavye.U.style.backgroundImage="url('grafikler/standart-bg.png')";
                document["sag_isaret"].src= temel_url + "grafikler/sag_isaret.jpg";
                break;
        case 86:document.klavye.V.style.background='black';
                document.klavye.V.style.backgroundImage="url('grafikler/standart-bg.png')";
                document["sol_isaret"].src= temel_url + "grafikler/sol_isaret.jpg";
                break;
        case 87:document.klavye.W.style.background='black';
                document.klavye.W.style.backgroundImage="url('grafikler/standart-bg.png')";
                document["sol_yuzuk"].src= temel_url + "grafikler/sol_yuzuk.jpg";
                break;
        case 88:document.klavye.X.style.background='black';
                document.klavye.X.style.backgroundImage="url('grafikler/standart-bg.png')";
                document["sol_yuzuk"].src= temel_url + "grafikler/sol_yuzuk.jpg";
                break;
        case 89:document.klavye.Y.style.background='black';
                document.klavye.Y.style.backgroundImage="url('grafikler/standart-bg.png')";
                document["sag_isaret"].src= temel_url + "grafikler/sag_isaret.jpg";
                break;
        case 90:document.klavye.Z.style.background='black';
                document.klavye.Z.style.backgroundImage="url('grafikler/standart-bg.png')";
                document["sol_serce"].src= temel_url + "grafikler/sol_serce.jpg";
                break;
        case 91:document.klavye.sekiz.style.background='black';
                document.klavye.sekiz.style.backgroundImage="url('grafikler/standart-bg.png')";
                document["sag_orta"].src= temel_url + "grafikler/sag_orta.jpg";
                break;
        case 92:document.klavye.yildiz.style.background='black';
                document.klavye.yildiz.style.backgroundImage="url('grafikler/standart-bg.png')";
                document["sag_serce"].src= temel_url + "grafikler/sag_serce.jpg";
                break;
        case 93:document.klavye.dokuz.style.background='black';
                document.klavye.dokuz.style.backgroundImage="url('grafikler/standart-bg.png')";
                document["sag_yuzuk"].src= temel_url + "grafikler/sag_yuzuk.jpg";
                break;
        case 94:document.klavye.uc.style.background='black';
                document.klavye.uc.style.backgroundImage="url('grafikler/standart-bg.png')";
                document["sol_orta"].src= temel_url + "grafikler/sol_orta.jpg";
                break;
        case 95:document.klavye.eksi.style.background='black';
                document.klavye.eksi.style.backgroundImage="url('grafikler/standart-bg.png')";
                document["sag_serce"].src= temel_url + "grafikler/sag_serce.jpg";
                break;
        case 96:document.klavye.iki.style.background='black';
                document.klavye.iki.style.backgroundImage="url('grafikler/standart-bg.png')";
                document["sol_yuzuk"].src= temel_url + "grafikler/sol_yuzuk.jpg";
                break;
        case 97:document.klavye.A.style.background='black';
                document.klavye.A.style.backgroundImage="url('grafikler/standart-bg.png')";
                document["sol_serce"].src= temel_url + "grafikler/sol_serce.jpg";
                break;
        case 98:document.klavye.B.style.background='black';
                document.klavye.B.style.backgroundImage="url('grafikler/standart-bg.png')";
                document["sol_isaret"].src= temel_url + "grafikler/sol_isaret.jpg";
                break;
        case 99:document.klavye.C.style.background='black';
                document.klavye.C.style.backgroundImage="url('grafikler/standart-bg.png')";
                document.klavye.C.style.backgroundImage="url('grafikler/standart-bg.png')";
                document["sol_orta"].src= temel_url + "grafikler/sol_orta.jpg";
                break;
        case 100:document.klavye.D.style.background='black';
                document.klavye.D.style.backgroundImage="url('grafikler/standart-bg.png')";
                 document["sol_orta"].src= temel_url + "grafikler/sol_orta.jpg";
                 break;
        case 101:document.klavye.E.style.background='black';
                document.klavye.E.style.backgroundImage="url('grafikler/standart-bg.png')";
                 document["sol_orta"].src= temel_url + "grafikler/sol_orta.jpg";
                 break;
        case 102:document.klavye.F.style.background='black';
                document.klavye.F.style.backgroundImage="url('grafikler/standart-bg.png')";
                 document["sol_isaret"].src= temel_url + "grafikler/sol_isaret.jpg";
                 break;
        case 103:document.klavye.G.style.background='black';
                document.klavye.G.style.backgroundImage="url('grafikler/standart-bg.png')";
                 document["sol_isaret"].src= temel_url + "grafikler/sol_isaret.jpg";
                 break;
        case 104:document.klavye.H.style.background='black';
                document.klavye.H.style.backgroundImage="url('grafikler/standart-bg.png')";
                 document["sag_isaret"].src= temel_url + "grafikler/sag_isaret.jpg";
                 break;
        case 105:document.klavye.ii.style.background='black';
                document.klavye.ii.style.backgroundImage="url('grafikler/standart-bg.png')";
                 document["sag_serce"].src= temel_url + "grafikler/sag_serce.jpg";
                 break;
        case 106:document.klavye.J.style.background='black';
                document.klavye.J.style.backgroundImage="url('grafikler/standart-bg.png')";
                 document["sag_isaret"].src= temel_url + "grafikler/sag_isaret.jpg";
                 break;
        case 107:document.klavye.K.style.background='black';
                 document.klavye.K.style.backgroundImage="url('grafikler/standart-bg.png')";
                 document["sag_orta"].src= temel_url + "grafikler/sag_orta.jpg";
                 break;
        case 108:document.klavye.L.style.background='black';
                 document.klavye.L.style.backgroundImage="url('grafikler/standart-bg.png')";
                 document["sag_yuzuk"].src= temel_url + "grafikler/sag_yuzuk.jpg";
                 break;
        case 109:document.klavye.M.style.background='black';
                 document.klavye.M.style.backgroundImage="url('grafikler/standart-bg.png')";
                 document["sag_isaret"].src= temel_url + "grafikler/sag_isaret.jpg";
                 break;
        case 110:document.klavye.N.style.background='black';
                 document.klavye.N.style.backgroundImage="url('grafikler/standart-bg.png')";
                 document["sag_isaret"].src= temel_url + "grafikler/sag_isaret.jpg";
                 break;
        case 111:document.klavye.O.style.background='black';
                 document.klavye.O.style.backgroundImage="url('grafikler/standart-bg.png')";
                 document.klavye.A.style.backgroundImage="url('grafikler/standart-bg.png')";
                 document["sag_yuzuk"].src= temel_url + "grafikler/sag_yuzuk.jpg";
                 break;
        case 112:document.klavye.P.style.background='black';
                 document.klavye.P.style.backgroundImage="url('grafikler/standart-bg.png')";
                 document["sag_serce"].src= temel_url + "grafikler/sag_serce.jpg";
                 break;
        case 113:document.klavye.Q.style.background='black';
                 document.klavye.Q.style.backgroundImage="url('grafikler/standart-bg.png')";
                 document["sol_serce"].src= temel_url + "grafikler/sol_serce.jpg";
                 break;
        case 114:document.klavye.R.style.background='black';
                 document.klavye.R.style.backgroundImage="url('grafikler/standart-bg.png')";
                 document["sol_isaret"].src= temel_url + "grafikler/sol_isaret.jpg";
                 break;
        case 115:document.klavye.S.style.background='black';
                 document.klavye.S.style.backgroundImage="url('grafikler/standart-bg.png')";
                 document["sol_yuzuk"].src= temel_url + "grafikler/sol_yuzuk.jpg";
                 break;
        case 116:document.klavye.T.style.background='black';
                 document.klavye.T.style.backgroundImage="url('grafikler/standart-bg.png')";
                 document["sol_isaret"].src= temel_url + "grafikler/sol_isaret.jpg";
                 break;
        case 117:document.klavye.U.style.background='black';
                 document.klavye.U.style.backgroundImage="url('grafikler/standart-bg.png')";
                 document["sag_isaret"].src= temel_url + "grafikler/sag_isaret.jpg";
                 break;
        case 118:document.klavye.V.style.background='black';
                 document.klavye.V.style.backgroundImage="url('grafikler/standart-bg.png')";
                 document["sol_isaret"].src= temel_url + "grafikler/sol_isaret.jpg";
                 break;
        case 119:document.klavye.W.style.background='black';
                 document.klavye.W.style.backgroundImage="url('grafikler/standart-bg.png')";
                 document["sol_yuzuk"].src= temel_url + "grafikler/sol_yuzuk.jpg";
                 break;
        case 120:document.klavye.X.style.background='black';
                 document.klavye.X.style.backgroundImage="url('grafikler/standart-bg.png')";
                 document["sol_yuzuk"].src= temel_url + "grafikler/sol_yuzuk.jpg";
                 break;
        case 121:document.klavye.Y.style.background='black';
                 document.klavye.Y.style.backgroundImage="url('grafikler/standart-bg.png')";
                 document["sag_isaret"].src= temel_url + "grafikler/sag_isaret.jpg";
                 break;
        case 122:document.klavye.Z.style.background='black';
                 document.klavye.Z.style.backgroundImage="url('grafikler/standart-bg.png')";
                 document["sol_serce"].src= temel_url + "grafikler/sol_serce.jpg";
                 break;
        case 123:document.klavye.yedi.style.background='black';
                 document.klavye.yedi.style.backgroundImage="url('grafikler/standart-bg.png')";
                 document["sag_isaret"].src= temel_url + "grafikler/sag_isaret.jpg";
                 break;
        case 124:document.klavye.kucuktur.style.background='black';
                 document.klavye.kucuktur.style.backgroundImage="url('grafikler/standart-bg.png')";
                 document["sol_serce"].src= temel_url + "grafikler/sol_serce.jpg";
                 break;
        case 125:document.klavye.sifir.style.background='black';
                 document.klavye.sifir.style.backgroundImage="url('grafikler/standart-bg.png')";
                 document["sag_serce"].src= temel_url + "grafikler/sag_serce.jpg";
                 break;
        case 126:document.klavye.uu.style.background='black';
                 document.klavye.uu.style.backgroundImage="url('grafikler/standart-bg.png')";
                 document["sag_serce"].src= temel_url + "grafikler/sag_serce.jpg";
                 break;
        case 127:document.klavye.del.style.background='black';
                 document.klavye.del.style.backgroundImage="url('grafikler/standart-bg.png')";
                 document["sag_serce"].src= temel_url + "grafikler/sag_serce.jpg";
                 break;
        case 287:document.klavye.gg.style.background='black';
                 document.klavye.gg.style.backgroundImage="url('grafikler/standart-bg.png')";
                 document["sag_serce"].src= temel_url + "grafikler/sag_serce.jpg";
                 break;
        case 286:document.klavye.gg.style.background='black';
                 document.klavye.gg.style.backgroundImage="url('grafikler/standart-bg.png')";
                 document["sag_serce"].src= temel_url + "grafikler/sag_serce.jpg";
                 break;
        case 252:document.klavye.uu.style.background='black';
                 document.klavye.uu.style.backgroundImage="url('grafikler/standart-bg.png')";
                 document["sag_serce"].src= temel_url + "grafikler/sag_serce.jpg";
                 break;
        case 220:document.klavye.uu.style.background='black';
                 document.klavye.uu.style.backgroundImage="url('grafikler/standart-bg.png')";
                 document["sag_serce"].src= temel_url + "grafikler/sag_serce.jpg";
                 break;
        case 351:document.klavye.ss.style.background='black';
                 document.klavye.ss.style.backgroundImage="url('grafikler/standart-bg.png')";
                 document["sag_serce"].src= temel_url + "grafikler/sag_serce.jpg";
                 break;
        case 350:document.klavye.ss.style.background='black';
                 document.klavye.ss.style.backgroundImage="url('grafikler/standart-bg.png')";
                 document["sag_serce"].src= temel_url + "grafikler/sag_serce.jpg";
                 break;
        case 305:document.klavye.I.style.background='black';
                 document.klavye.I.style.backgroundImage="url('grafikler/standart-bg.png')";
                 document["sag_orta"].src= temel_url + "grafikler/sag_orta.jpg";
                 break;
        case 304:document.klavye.ii.style.background='black';
                 document.klavye.ii.style.backgroundImage="url('grafikler/standart-bg.png')";
                 document["sag_serce"].src= temel_url + "grafikler/sag_serce.jpg";
                 break;
        case 246:document.klavye.oo.style.background='black';
                 document.klavye.oo.style.backgroundImage="url('grafikler/standart-bg.png')";
                 document["sag_orta"].src= temel_url + "grafikler/sag_orta.jpg";
                 break;
        case 214:document.klavye.oo.style.background='black';
                 document.klavye.oo.style.backgroundImage="url('grafikler/standart-bg.png')";
                 document["sag_orta"].src= temel_url + "grafikler/sag_orta.jpg";
                 break;
        case 231:document.klavye.cc.style.background='black';
                 document.klavye.cc.style.backgroundImage="url('grafikler/standart-bg.png')";
                 document["sag_yuzuk"].src= temel_url + "grafikler/sag_yuzuk.jpg";
                 break;
        case 199:document.klavye.cc.style.background='black';
                 document.klavye.cc.style.backgroundImage="url('grafikler/standart-bg.png')";
                 document["sag_yuzuk"].src= temel_url + "grafikler/sag_yuzuk.jpg";
                 break;
       }

}
